import { 
  LayoutDashboard, 
  Users, 
  FileText, 
  Settings, 
  Search, 
  Bell, 
  Plus, 
  MoreHorizontal,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  Download,
  Trash2,
  GripVertical,
  Camera,
  CheckCircle2,
  XCircle,
  Clock,
  Briefcase,
  Smartphone,
  Sparkles,
  Menu,
  X
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Candidates: Users,
  Forms: FileText,
  Settings: Settings,
  Search: Search,
  Bell: Bell,
  Plus: Plus,
  More: MoreHorizontal,
  Right: ChevronRight,
  Left: ChevronLeft,
  Down: ChevronDown,
  Up: ChevronUp,
  Download: Download,
  Delete: Trash2,
  Drag: GripVertical,
  Camera: Camera,
  Check: CheckCircle2,
  Reject: XCircle,
  Pending: Clock,
  Work: Briefcase,
  Mobile: Smartphone,
  AI: Sparkles,
  Menu: Menu,
  Close: X
};